// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oG0_QrH8PwG-KLIvGnXyoNTlWM-nfzg',
    appId: '1:418314284569:web:dd254174e2d4d7d7404488',
    messagingSenderId: '418314284569',
    projectId: 'readright-fe68d',
    authDomain: 'readright-fe68d.firebaseapp.com',
    storageBucket: 'readright-fe68d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfn397GMQODiUSbqCcDrtki6WYj0go2PU',
    appId: '1:418314284569:android:60c1ec114d907da9404488',
    messagingSenderId: '418314284569',
    projectId: 'readright-fe68d',
    storageBucket: 'readright-fe68d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5oG0_QrH8PwG-KLIvGnXyoNTlWM-nfzg',
    appId: '1:418314284569:web:91bc869c5f055d4b404488',
    messagingSenderId: '418314284569',
    projectId: 'readright-fe68d',
    authDomain: 'readright-fe68d.firebaseapp.com',
    storageBucket: 'readright-fe68d.firebasestorage.app',
  );
}
